### ISSUE TITLE
[BUG] createVideoMessageFromFullPath return ""

### ISSUE THREAD

**Issue by albert-get** [openimsdk/openim-sdk-core#778]
### OpenIM SDK Version

flutter_openim_sdk: 3.8.1

### OpenIM Server Version

release-v3.8.1

### SDK Platform

iOS SDK

### Device Model

iPhone 15 Pro simulator

### Operating System Version

ios 17.0

### Bug Description and Steps to Reproduce

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: FormatException: Unexpected end of input (at character 1)

^

#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1465:5)
convert_patch.dart:1465
#1      _ChunkedJsonParser.close (dart:convert-patch/convert_patch.dart:499:7)
convert_patch.dart:499
#2      _parseJson (dart:convert-patch/convert_patch.dart:37:10)
convert_patch.dart:37
#3      JsonDecoder.convert (dart:convert/json.dart:610:36)
json.dart:610
#4      JsonCodec.decode (dart:convert/json.dart:216:41)
json.dart:216
#5      jsonDecode (dart:convert/json.dart:155:10)
json.dart:155
#6      Utils.formatJson (package:flutter_openim_sdk/src/utils.dart:11:46)
utils.dart:11
#7      Utils.toObj (package:flutter_openim_sdk/src/utils.dart:7:71)
utils.dart:7
#8      MessageManager.createVideoMessageFromFullPath.<anonymous closure> (package:flutter_openim_sdk/src/manager/im_message_manager.dart:314:34)
im_message_manager.dart:314
<asynchronous suspension>
#9      ChatPage.build.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:socialclient/pages/chat.dart:332:52)
chat.dart:332
<asynchronous suspension>

### Screenshots Link

videoPath:"/Users/harry/Library/Developer/CoreSimulator/Devices/ABF604E9-7AA9-468A-B7C1-60C9CDE5080B/data/Containers/Data/Application/12E96535-1E54-4660-AC0A-74DB66A3D0B9/tmp/image_picker_68F21A1C-DF6D-477D-BA63-409C8B85E694-99143-00005A18A6B131F259a4_core_5017_9782a4cfeb09ed1a42449bcac3dd4b80.mp4",
videoType:"video/mp4",
duration:287,
snapshotPath:''
createImageMessageFromFullPath 是可以成功的，在debug模式下，没有内部sdk的日志，直接报错

**Comment by codingOOatOOyi** [comment]
不要用这个项目，垃圾的要死，坑死你，这个项目主打的怎么复杂就怎么来，怎么赚钱就怎么来

**Comment by skiffer-git** [comment]
Please confirm that the parameters are correct.
